### ISSUE TITLE
Open a file in a script

### ISSUE THREAD

**Issue by tjthejuggler** [zobnin/aiolauncher_scripts#21]
Up until today I had a custom widget that would show what was in a file located at /storage/emulated/0/Documents/myfile.md however now with custom widgets removed I'm trying to do this with Lua scripting. I have gotten files:read("myfile.md","r") to work, but it needs the file to be deep inside android/data/ru.. and I need to be able to read files that are not all the way in there. I've tried doing io.open , but it seems like aio doesn't have access to external files or something. Is it now impossible to have a widget show what is in one of my files? Thanks so much!

**Comment by zobnin** [comment]
Yes. Modern android versions restricts access to storage. As workaround you can connect script with tasker profile that reads your file. See "Tasker" section in the README.

**Comment by tjthejuggler** [comment]
Ah! Tasker, I should have known. Thanks so much for the info, the fast reply, working on such an awesome launcher, everything! I really appreciate it.

**Comment by zobnin** [comment]
Thank you
