### ISSUE TITLE
Buttons and text in same widget

### ISSUE THREAD

**Issue by cuh7b5** [zobnin/aiolauncher_scripts#22]
Is there a way to use both buttons and texts (or tables) in the same widget?
Or can I create a meta widget containing my own scripts to mix different ui element types? I tried ui:build(table) but as I can see it only accepts some built-in widgets like 'battery' or 'ram'.

**Comment by zobnin** [comment]
I gave up on this idea because it greatly complicated the API without giving much advantage. Perhaps, if you explain your task I will tell you how to solve it using standard APIs.

**Comment by cuh7b5** [comment]
I see. Thanks anyway for this great tool! 
I wanted to create a script with media buttons to control my PC. I wanted to place a text beneath the button row showing what's playing. I use a button now with the text inside, this is ok.

**Comment by zobnin** [comment]
I will most likely add a more flexible way to create an UI in the future.
