### ISSUE TITLE
SSH Buttons widget - exception throws after first successful execution

### ISSUE THREAD

**Issue by barser** [zobnin/aiolauncher_scripts#26]
For example there are three buttons with primitive shell commands:

![Screenshot_20240519_104332.jpg](https://github.com/zobnin/aiolauncher_scripts/assets/8071147/b3436f5a-e468-4521-8eb0-4accfeb681a2)

All buttons are configured to show its result in toast 

After executed button "uname -a" there is successful result. But after that when pressing any other (or previous button again) there is an exception:

![Screenshot_20240519_104302.jpg](https://github.com/zobnin/aiolauncher_scripts/assets/8071147/664906bf-d0b4-4df0-b3c5-2c9247e64be6)

**Comment by zobnin** [comment]
Wrong repo. Right one: https://github.com/zobnin/aio_ssh_button_plugin
