### ISSUE TITLE
CLEARTEXT communication not permitted by network security policy

### ISSUE THREAD

**Issue by cuh7b5** [zobnin/aiolauncher_scripts#28]
This script:

```
function on_resume()
    http:get("http://cuh.sdf.org/test.html")
end


function on_network_result(result)
    ui:show_text(result)
end

function on_network_error(error)
    ui:show_text(error)
end
```
gives this error message instead of the network result:
"CLEARTEXT communication to cuh.sdf.org not permitted by network security policy"

I believe that plain http is no longer permitted for http:get, only https.

Is there a way to use plain http sites?
It worked few weeks ago.

Thanks

**Comment by zobnin** [comment]
Will be fixed in the next version. Thank you.
